name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:

permissions:
  contents: write  # Permite escrita no repositório

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: guikbit
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v3.1.0  # Atualizar para a versão mais recente
        with:
          target_branch: gh-pages  # Verifique se o branch de destino é correto
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
